### ISSUE TITLE
JETracker really needs to be NSObject?

### ISSUE THREAD

**Issue by ssouzawallace** [justeat/JustTrack#1]
There is some strong constraint to the @obj requirement in the `JETracker` protocol?
I've tried to make an implementation of our trackers with their names concentrated in an enum. Like follows.
But the @obj is causing an segmentation fault 11 while using the computed var `name`. Removing the @obj everything works just fine.

MyTrackerProtocol:

```swift
enum TrackerType: String {
    case googleAnalytics    = "GoogleAnalytics"
    case localytics         = "Localytics"
    case firebase           = "Firebase"
    case answers            = "Answers"
}

protocol Tracker: JETracker {
    var type: TrackerType { get }
}

extension Tracker {
    var name: String {
        return type.rawValue
    }
}
```

**Comment by federicocappelli** [comment]
Hi @ssouzawallace 
**@objc** is there in order to expose the protocol to Objective-C, that is actively supported by JustTrack.

![screen shot 2017-02-06 at 16 31 06](https://cloud.githubusercontent.com/assets/1489236/22655976/c369b17c-ec89-11e6-93d8-4a8293fa1d93.png)

`enum TrackerType: String` and protocol extension are not supported in obj-c

try something like:

```
@objc enum TrackerType: NSInteger {
    case googleAnalytics
    case localytics
    case firebase
    case answers
}

@objc protocol Tracker: JETracker {
    var type: TrackerType { get }
}

@objc class TrackerExample: NSObject,Tracker {
    var type: TrackerType

    var name: String {
        get
        {
            switch self.type {
            case .googleAnalytics:
                return "googleAnalytics"
            case .localytics:
                return "localytics"
            case .firebase:
                return "firebase"
            case .answers:
                return "answers"
            }
        }
    }
    
    required init(configuration: Configuration?) {
        self.type = .googleAnalytics
    }
    
    func trackEvent(_ name: String, payload: Payload, completion: (_ success: Bool) -> Void) {
        //???
        completion(true)
    }
}

```

If you have any other question or suggestion we can re-open the issue.
